### ISSUE TITLE
Orientation issue during animation with UIImageView as reference view

### ISSUE THREAD

**Issue by lrossi** [NYTimes/NYTPhotoViewer#115] opened 2016-01-09 17:15 UTC
I have encountered an issue during the opening and closing animations when the following conditions are met:

-  Delegate's `photosViewController:referenceViewForPhoto:` returns an `UIImageView`.
-  The `UIImageView`'s image is a photo taken with the device in portrait orientation (i.e. the `UIImage` has meaningful orientation informations associated).

If this is the case, the image is shown in the wrong orientation during the animation:
![orientation-issue](https://cloud.githubusercontent.com/assets/2843411/12217269/f89bee42-b6fb-11e5-9ec2-bdbf85f7143a.gif)

[Here](https://github.com/NYTimes/NYTPhotoViewer/files/83768/TestPortrait_Issue.zip) you find a simple demo project reproducing the issue. The project is build against the latest iOS 9 SDK and I have tested it on iOS 8 & 9 devices with the same results.

By tracking down the issue, it seems to be related to the `newAnimationViewFromView:` method of `NYTPhotoTransitionAnimator`, and to the following lines in particular:

```objc
if (view.layer.contents) {
    animationView = [[UIView alloc] initWithFrame:view.frame];
    animationView.layer.contents = view.layer.contents;
    animationView.layer.bounds = view.layer.bounds;
    animationView.layer.cornerRadius = view.layer.cornerRadius;
    animationView.layer.masksToBounds = view.layer.masksToBounds;
    animationView.contentMode = view.contentMode;
    animationView.transform = view.transform;
}
```

When `view` is a `UIImageView`, its layer's `contents` is a `CGImage` and that seems to strip out the orientation information of the corresponding `UIImage`. By quick looking at the variables in the debugger, the resulting `animationView` appears to be rotated and doesn't look the same as the original `view`.

This is not an issue with `UIImage`-s that don't store meta-informations about their own orientation, but it seems to be a problem with—at least—portrait image taken from the device's camera.

At the moment I'm using a patch (that I am about to send as pull request) addressing `UIImageView`-s to overcome this problem. [Here](https://github.com/NYTimes/NYTPhotoViewer/files/83769/TestPortrait_Fix.zip) you find another version of the demo project with the patch applied.

Thanks!

**Comment by cdzombak** [comment] 2016-01-26 14:52
closed by #116

**Closed by cdzombak** 2016-01-26 14:52 UTC

**Comment by bcapps** [comment] 2016-02-02 19:08
I may be a little late to the game here, but I was not able to reproduce this issue with he sample project provided above using an iPhone 6 on iOS 9. Is there something special required beyond the steps mentioned above?

**Comment by cdzombak** [comment] 2016-02-02 19:46
@bcapps I just tried & am able to repro on iPhone 6S & latest iOS 9.2.x. Did you pick a photo which was taken on your device, in portrait orientation?

![2016-02-02 14_46_30](https://cloud.githubusercontent.com/assets/102904/12762137/c77a05ce-c9bb-11e5-99f8-0f685ac1adf8.gif)
