### ISSUE TITLE
No view controller managing visible view

### ISSUE THREAD

**Issue by fysteven** [nytimes/NYTPhotoViewer#279] opened 2019-04-09 04:15 UTC
Fatal Exception: NSInternalInconsistencyException
No view controller managing visible view <UIView: 0x15be36210; frame = (0 0; 414 896); autoresize = W+H; gestureRecognizers = <NSArray: 0x28089e6d0>; layer = <CALayer: 0x280688fc0>>

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1a4259eb8 __exceptionPreprocess
1  libobjc.A.dylib                0x1a3453f18 objc_exception_throw
2  CoreFoundation                 0x1a416bce0 +[_CFXNotificationTokenRegistration keyCallbacks]
3  Foundation                     0x1a4c6d0fc -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKitCore                      0x1d18c0184 -[UIPageViewController queuingScrollView:didEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:]
5  UIKitCore                      0x1d18caa80 -[_UIQueuingScrollView _notifyDelegateDidEndManualScroll:toRevealView:direction:animated:didFinish:didComplete:]
6  UIKitCore                      0x1d18ccce8 -[_UITransitionState cleanupWithFinishedState:completedState:]
7  UIKitCore                      0x1d18c953c -[_UIQueuingScrollView _cleanUpCompletionState:didFinish:didComplete:]
8  UIKitCore                      0x1d18cb5a4 -[_UIQueuingScrollView _commitGestureDrivenScrollRevealingView:concealingView:inDirection:canComplete:]
9  UIKitCore                      0x1d18cbfc0 __54-[_UIQueuingScrollView _didScrollWithAnimation:force:]_block_invoke
10 UIKitCore                      0x1d18cba80 -[_UIQueuingScrollView _didScrollWithAnimation:force:]
11 UIKitCore                      0x1d18c7630 -[_UIQueuingScrollView layoutSubviews]
12 UIKitCore                      0x1d23ed13c -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
13 libobjc.A.dylib                0x1a344f2a4 -[NSObject performSelector:withObject:]
14 QuartzCore                     0x1a88fe110 -[CALayer layoutSublayers]
15 QuartzCore                     0x1a88fe3f0 CA::Layer::layout_if_needed(CA::Transaction*)
16 QuartzCore                     0x1a8861c18 CA::Context::commit_transaction(CA::Transaction*)
17 QuartzCore                     0x1a8891140 CA::Transaction::commit()
18 QuartzCore                     0x1a87cbc04 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
19 QuartzCore                     0x1a8898798 display_timer_callback(__CFMachPort*, void*, long, void*)
20 CoreFoundation                 0x1a41c0538 __CFMachPortPerform
21 CoreFoundation                 0x1a41e8bc8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
22 CoreFoundation                 0x1a41e82c0 __CFRunLoopDoSource1
23 CoreFoundation                 0x1a41e2e28 __CFRunLoopRun
24 CoreFoundation                 0x1a41e22e8 CFRunLoopRunSpecific
25 GraphicsServices               0x1a6496be8 GSEventRunModal
26 UIKitCore                      0x1d1f24088 UIApplicationMain
27 photo-safe                     0x102e9f03c main (main.m:14)
28 libdyld.dylib                  0x1a3c95050 start

**Comment by mr-fixit** [comment] 2020-12-09 04:05
i'm closing this because i can't see how this relates to NYTPhotoViewer. if you have further details, perhaps a sample project and the steps with which to reproduce this crash, please add them

**Closed by mr-fixit** 2020-12-09 04:05 UTC
