### ISSUE TITLE
photosViewController:didDisplayPhoto:atIndex: is not called for the initial photo.

### ISSUE THREAD

**Issue by heikkihautala** [NYTimes/NYTPhotoViewer#42] opened 2015-04-10 09:57 UTC
NYTPhotosViewControllerDelegate’s photosViewController:didDisplayPhoto:atIndex: is not called for the initial photo.

**Comment by bcapps** [comment] 2015-04-10 14:15
This was originally intended to reflect Apple's general approach with delegates like that, where the delegate is only called upon user interaction, not upon programmatic setting (which in this case would be programmatic setting of the initial photo or `moveToPhoto:`).

So, of course it can be changed based on what NYT thinks, but originally this was intended behavior.

**Comment by mattbischoff** [comment] 2015-04-10 19:29
I totally agree with @bcapps here. This is nearly every `UIKit` delegate works and it’d be good to stay consistent. I recommend closing this issue.

cc @Twigz

**Comment by heikkihautala** [comment] 2015-04-13 06:00
Ha, I should have read the documentation of the method :). The method name was a little misleading. Maybe the method could be renamed to better describe the difference? For example "didMoveToPhoto"?

**Closed** 2015-05-01 14:34 UTC
Labels: bug
