### ISSUE TITLE
delegate method didDisplayPhoto doesn't get called for first photo

### ISSUE THREAD

**Issue by ipedro** [NYTimes/NYTPhotoViewer#119] opened 2016-01-13 06:13 UTC
Currently this method is only called when there's a pageView change, from:

`- (void)pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:`

Ideally would be called as well from:

 `- (void)setupPageViewControllerWithInitialPhoto:`

**Comment by cdzombak** [comment] 2016-01-13 15:13
closing as a duplicate of #95

**Closed by cdzombak** 2016-01-13 15:13 UTC
Labels: duplicate
