### ISSUE TITLE
init methods should have a delegate parameter

### ISSUE THREAD

**Issue by livings124** [NYTimes/NYTPhotoViewer#110] opened 2016-01-04 19:31 UTC
The init methods call commonInitWithPhotos:initialPhoto:, which call setupPageViewControllerWithInitialPhoto:, which calls newPhotoViewControllerForPhoto:, which accesses the delegate. Currently there's no way for the delegate to be set at that point.

**Comment by bcapps** [comment] 2016-01-04 19:37
This seems like it may be a duplicate of https://github.com/NYTimes/NYTPhotoViewer/issues/95

**Comment by cdzombak** [comment] 2016-01-04 20:06
> This seems like it may be a duplicate of #95

with different words, but yes, that's true.

**Closed by cdzombak** 2016-01-04 20:06 UTC
Labels: duplicate
